[project]
name = "call-me-maybe"
version = "0.1.0"
description = "Constrained decoding function-calling tool using Qwen3-0.6B"
requires-python = ">=3.10"
dependencies = [
    "pydantic>=2.0",
    "numpy>=1.26",
    "flake8>=7.3.0",
    "mypy>=1.19.1",
    "llm-sdk",
]

[tool.uv.sources]
llm-sdk = { workspace = true }

[tool.uv.workspace]
members = ["llm_sdk"]
